/*
 * This file is generated by jOOQ.
 */
package com.invillia.acme.jooq;


import com.invillia.acme.jooq.tables.Order;
import com.invillia.acme.jooq.tables.OrderItem;
import com.invillia.acme.jooq.tables.OrderItemStatus;
import com.invillia.acme.jooq.tables.OrderStatus;
import com.invillia.acme.jooq.tables.Payment;
import com.invillia.acme.jooq.tables.PaymentStatus;
import com.invillia.acme.jooq.tables.Store;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Acme extends SchemaImpl {

    private static final long serialVersionUID = -810269800;

    /**
     * The reference instance of <code>acme</code>
     */
    public static final Acme ACME = new Acme();

    /**
     * The table <code>acme.order</code>.
     */
    public final Order ORDER = com.invillia.acme.jooq.tables.Order.ORDER;

    /**
     * The table <code>acme.order_item</code>.
     */
    public final OrderItem ORDER_ITEM = com.invillia.acme.jooq.tables.OrderItem.ORDER_ITEM;

    /**
     * The table <code>acme.order_item_status</code>.
     */
    public final OrderItemStatus ORDER_ITEM_STATUS = com.invillia.acme.jooq.tables.OrderItemStatus.ORDER_ITEM_STATUS;

    /**
     * The table <code>acme.order_status</code>.
     */
    public final OrderStatus ORDER_STATUS = com.invillia.acme.jooq.tables.OrderStatus.ORDER_STATUS;

    /**
     * The table <code>acme.payment</code>.
     */
    public final Payment PAYMENT = com.invillia.acme.jooq.tables.Payment.PAYMENT;

    /**
     * The table <code>acme.payment_status</code>.
     */
    public final PaymentStatus PAYMENT_STATUS = com.invillia.acme.jooq.tables.PaymentStatus.PAYMENT_STATUS;

    /**
     * The table <code>acme.store</code>.
     */
    public final Store STORE = com.invillia.acme.jooq.tables.Store.STORE;

    /**
     * No further instances allowed
     */
    private Acme() {
        super("acme", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Order.ORDER,
            OrderItem.ORDER_ITEM,
            OrderItemStatus.ORDER_ITEM_STATUS,
            OrderStatus.ORDER_STATUS,
            Payment.PAYMENT,
            PaymentStatus.PAYMENT_STATUS,
            Store.STORE);
    }
}
