/*
 * This file is generated by jOOQ.
 */
package com.invillia.acme.jooq;


import com.invillia.acme.jooq.tables.Order;
import com.invillia.acme.jooq.tables.OrderItem;
import com.invillia.acme.jooq.tables.OrderItemStatus;
import com.invillia.acme.jooq.tables.OrderStatus;
import com.invillia.acme.jooq.tables.Payment;
import com.invillia.acme.jooq.tables.PaymentStatus;
import com.invillia.acme.jooq.tables.Store;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in acme
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>acme.order</code>.
     */
    public static final Order ORDER = com.invillia.acme.jooq.tables.Order.ORDER;

    /**
     * The table <code>acme.order_item</code>.
     */
    public static final OrderItem ORDER_ITEM = com.invillia.acme.jooq.tables.OrderItem.ORDER_ITEM;

    /**
     * The table <code>acme.order_item_status</code>.
     */
    public static final OrderItemStatus ORDER_ITEM_STATUS = com.invillia.acme.jooq.tables.OrderItemStatus.ORDER_ITEM_STATUS;

    /**
     * The table <code>acme.order_status</code>.
     */
    public static final OrderStatus ORDER_STATUS = com.invillia.acme.jooq.tables.OrderStatus.ORDER_STATUS;

    /**
     * The table <code>acme.payment</code>.
     */
    public static final Payment PAYMENT = com.invillia.acme.jooq.tables.Payment.PAYMENT;

    /**
     * The table <code>acme.payment_status</code>.
     */
    public static final PaymentStatus PAYMENT_STATUS = com.invillia.acme.jooq.tables.PaymentStatus.PAYMENT_STATUS;

    /**
     * The table <code>acme.store</code>.
     */
    public static final Store STORE = com.invillia.acme.jooq.tables.Store.STORE;
}
