/*
 * This file is generated by jOOQ.
 */
package com.invillia.acme.jooq.tables;


import com.invillia.acme.jooq.Acme;
import com.invillia.acme.jooq.Indexes;
import com.invillia.acme.jooq.Keys;
import com.invillia.acme.jooq.tables.records.OrderItemStatusRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderItemStatus extends TableImpl<OrderItemStatusRecord> {

    private static final long serialVersionUID = 1272904346;

    /**
     * The reference instance of <code>acme.order_item_status</code>
     */
    public static final OrderItemStatus ORDER_ITEM_STATUS = new OrderItemStatus();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrderItemStatusRecord> getRecordType() {
        return OrderItemStatusRecord.class;
    }

    /**
     * The column <code>acme.order_item_status.id</code>.
     */
    public final TableField<OrderItemStatusRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>acme.order_item_status.name</code>.
     */
    public final TableField<OrderItemStatusRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * Create a <code>acme.order_item_status</code> table reference
     */
    public OrderItemStatus() {
        this(DSL.name("order_item_status"), null);
    }

    /**
     * Create an aliased <code>acme.order_item_status</code> table reference
     */
    public OrderItemStatus(String alias) {
        this(DSL.name(alias), ORDER_ITEM_STATUS);
    }

    /**
     * Create an aliased <code>acme.order_item_status</code> table reference
     */
    public OrderItemStatus(Name alias) {
        this(alias, ORDER_ITEM_STATUS);
    }

    private OrderItemStatus(Name alias, Table<OrderItemStatusRecord> aliased) {
        this(alias, aliased, null);
    }

    private OrderItemStatus(Name alias, Table<OrderItemStatusRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> OrderItemStatus(Table<O> child, ForeignKey<O, OrderItemStatusRecord> key) {
        super(child, key, ORDER_ITEM_STATUS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Acme.ACME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ORDER_ITEM_STATUS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<OrderItemStatusRecord> getPrimaryKey() {
        return Keys.KEY_ORDER_ITEM_STATUS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<OrderItemStatusRecord>> getKeys() {
        return Arrays.<UniqueKey<OrderItemStatusRecord>>asList(Keys.KEY_ORDER_ITEM_STATUS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderItemStatus as(String alias) {
        return new OrderItemStatus(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderItemStatus as(Name alias) {
        return new OrderItemStatus(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public OrderItemStatus rename(String name) {
        return new OrderItemStatus(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrderItemStatus rename(Name name) {
        return new OrderItemStatus(name, null);
    }
}
