/*
 * This file is generated by jOOQ.
 */
package com.invillia.acme.jooq;


import com.invillia.acme.jooq.tables.Order;
import com.invillia.acme.jooq.tables.OrderItem;
import com.invillia.acme.jooq.tables.OrderStatus;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in acme
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>acme.order</code>.
     */
    public static final Order ORDER = com.invillia.acme.jooq.tables.Order.ORDER;

    /**
     * The table <code>acme.order_item</code>.
     */
    public static final OrderItem ORDER_ITEM = com.invillia.acme.jooq.tables.OrderItem.ORDER_ITEM;

    /**
     * The table <code>acme.order_status</code>.
     */
    public static final OrderStatus ORDER_STATUS = com.invillia.acme.jooq.tables.OrderStatus.ORDER_STATUS;
}
