/*
 * This file is generated by jOOQ.
 */
package com.invillia.acme.jooq;


import com.invillia.acme.jooq.tables.Payment;
import com.invillia.acme.jooq.tables.PaymentStatus;
import com.invillia.acme.jooq.tables.records.PaymentRecord;
import com.invillia.acme.jooq.tables.records.PaymentStatusRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>acme</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PaymentRecord> KEY_PAYMENT_PRIMARY = UniqueKeys0.KEY_PAYMENT_PRIMARY;
    public static final UniqueKey<PaymentStatusRecord> KEY_PAYMENT_STATUS_PRIMARY = UniqueKeys0.KEY_PAYMENT_STATUS_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<PaymentRecord, PaymentRecord> PAYMENT_IBFK_1 = ForeignKeys0.PAYMENT_IBFK_1;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<PaymentRecord> KEY_PAYMENT_PRIMARY = Internal.createUniqueKey(Payment.PAYMENT, "KEY_payment_PRIMARY", Payment.PAYMENT.ID);
        public static final UniqueKey<PaymentStatusRecord> KEY_PAYMENT_STATUS_PRIMARY = Internal.createUniqueKey(PaymentStatus.PAYMENT_STATUS, "KEY_payment_status_PRIMARY", PaymentStatus.PAYMENT_STATUS.ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<PaymentRecord, PaymentRecord> PAYMENT_IBFK_1 = Internal.createForeignKey(com.invillia.acme.jooq.Keys.KEY_PAYMENT_PRIMARY, Payment.PAYMENT, "payment_ibfk_1", Payment.PAYMENT.ID_PAYMENT_STATUS);
    }
}
