/*
 * This file is generated by jOOQ.
 */
package com.invillia.acme.jooq;


import com.invillia.acme.jooq.tables.Payment;
import com.invillia.acme.jooq.tables.PaymentStatus;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in acme
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>acme.payment</code>.
     */
    public static final Payment PAYMENT = com.invillia.acme.jooq.tables.Payment.PAYMENT;

    /**
     * The table <code>acme.payment_status</code>.
     */
    public static final PaymentStatus PAYMENT_STATUS = com.invillia.acme.jooq.tables.PaymentStatus.PAYMENT_STATUS;
}
