/*
 * This file is generated by jOOQ.
 */
package com.invillia.acme.jooq.tables.records;


import com.invillia.acme.jooq.tables.OrderItem;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderItemRecord extends UpdatableRecordImpl<OrderItemRecord> implements Record6<Integer, BigDecimal, Integer, Integer, Boolean, String> {

    private static final long serialVersionUID = -2112126187;

    /**
     * Setter for <code>acme.order_item.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>acme.order_item.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>acme.order_item.unitPrice</code>.
     */
    public void setUnitprice(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for <code>acme.order_item.unitPrice</code>.
     */
    public BigDecimal getUnitprice() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>acme.order_item.quantity</code>.
     */
    public void setQuantity(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>acme.order_item.quantity</code>.
     */
    public Integer getQuantity() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>acme.order_item.id_order</code>.
     */
    public void setIdOrder(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>acme.order_item.id_order</code>.
     */
    public Integer getIdOrder() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>acme.order_item.refunded</code>.
     */
    public void setRefunded(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>acme.order_item.refunded</code>.
     */
    public Boolean getRefunded() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>acme.order_item.description</code>.
     */
    public void setDescription(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>acme.order_item.description</code>.
     */
    public String getDescription() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, BigDecimal, Integer, Integer, Boolean, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, BigDecimal, Integer, Integer, Boolean, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return OrderItem.ORDER_ITEM.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field2() {
        return OrderItem.ORDER_ITEM.UNITPRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return OrderItem.ORDER_ITEM.QUANTITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return OrderItem.ORDER_ITEM.ID_ORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return OrderItem.ORDER_ITEM.REFUNDED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return OrderItem.ORDER_ITEM.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component2() {
        return getUnitprice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getIdOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component5() {
        return getRefunded();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value2() {
        return getUnitprice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getIdOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getRefunded();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderItemRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderItemRecord value2(BigDecimal value) {
        setUnitprice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderItemRecord value3(Integer value) {
        setQuantity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderItemRecord value4(Integer value) {
        setIdOrder(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderItemRecord value5(Boolean value) {
        setRefunded(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderItemRecord value6(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderItemRecord values(Integer value1, BigDecimal value2, Integer value3, Integer value4, Boolean value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderItemRecord
     */
    public OrderItemRecord() {
        super(OrderItem.ORDER_ITEM);
    }

    /**
     * Create a detached, initialised OrderItemRecord
     */
    public OrderItemRecord(Integer id, BigDecimal unitprice, Integer quantity, Integer idOrder, Boolean refunded, String description) {
        super(OrderItem.ORDER_ITEM);

        set(0, id);
        set(1, unitprice);
        set(2, quantity);
        set(3, idOrder);
        set(4, refunded);
        set(5, description);
    }
}
