/*
 * This file is generated by jOOQ.
 */
package com.invillia.acme.jooq;


import com.invillia.acme.jooq.tables.Store;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in acme
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>acme.store</code>.
     */
    public static final Store STORE = com.invillia.acme.jooq.tables.Store.STORE;
}
